OnlinePay/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Pay import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pay/',include('Pay.urls',namespace='pay')),
    url(r'^$',views.online_pay),
]

Pay/urls.py
from django.conf.urls import url

from Pay import views

urlpatterns = [
    url(r'^onlinepay/', views.online_pay, name='index'),
    url(r'^payjin66/', views.pay_jin66, name='jin66'),
    url(r'^paysancai/', views.pay_sancai, name='sancai'),
    url(r'^payrenshenguo/', views.pay_renshenguo, name='renshenguo'),
    url(r'^payxingshendan/', views.pay_xingshendan, name='xingshendan'),
    url(r'^payjineng/', views.pay_jineng, name='jineng'),
    url(r'^controllerjin66/', views.controller_pay_jin66, name='cjin66'),
    url(r'^controllersancai/', views.controller_pay_sancai, name='csancai'),
    url(r'^controllerrenshenguo/', views.controller_pay_renshenguo, name='crenshenguo'),
    url(r'^controllerxingshendan/', views.controller_pay_xingshendan, name='cxingshendan'),
    url(r'^controllerjineng/', views.controller_pay_jineng, name='cjineng'),
    url(r'^getpaidinfo/', views.get_paidinfo, name='paidinfo'),

    url(r'^myattribute/', views.my_attribute, name='myattribute'),

]

Pay/models.py
from django.db import models


class OrderList(models.Model):
    order_info = models.CharField(max_length=200)
    order_success = models.CharField(max_length=10,default=0)

Pay/views.py
# import json
import os
import time
import hashlib
from KEYS.keys import SECRET_KEYS
from OnlinePay.settings import BASE_DIR

from django.http import HttpResponse
from django.shortcuts import render
import paramiko

from Pay.models import OrderList
from Pay.tasks import take_item


def online_pay(request):
    context = {
        "title": "天道酬勤玩家自助中心"
    }
    return render(request, 'mz.html', context=context)


# 金柳露
def pay_jin66(request):
    context = {
        "title": "金柳露礼包"
    }
    return render(request, 'pay_jin66.html', context=context)


def controller_pay_jin66(request):
    extdata = request.POST.get('extdata')
    print(extdata)
    if extdata == "110":
        paymoney = 10  # 10
    elif extdata == "111":
        paymoney = 20  # 20
    elif extdata == "112":
        paymoney = 50  # 50
    context = {
        "gameuser": request.POST.get('gameuser'),
        "paymoney": paymoney,
        "extdata": extdata,
    }
    return render(request, 'jump.html', context=context)


# 三才勾玉
def pay_sancai(request):
    context = {
        "title": "三才勾玉礼包"
    }
    return render(request, 'pay_sancai.html', context=context)


def controller_pay_sancai(request):
    extdata = request.POST.get('extdata')
    if extdata == "113":
        paymoney = 58  # 58
    context = {
        "gameuser": request.POST.get('gameuser'),
        "paymoney": paymoney,
        "extdata": extdata,
    }
    return render(request, 'jump.html', context=context)


# 人参果
def pay_renshenguo(request):
    context = {
        "title": "人参果礼包"
    }
    return render(request, 'pay_renshenguo.html', context=context)


def controller_pay_renshenguo(request):
    extdata = request.POST.get('extdata')
    print(extdata)
    if extdata == "114":
        paymoney = 10  # 10
    context = {
        "gameuser": request.POST.get('gameuser'),
        "paymoney": paymoney,
        "extdata": extdata,
    }
    return render(request, 'jump.html', context=context)


# 醒神丹

def pay_xingshendan(request):
    context = {
        "title": "醒神丹礼包"
    }
    return render(request, 'pay_xingshendan.html', context=context)


def controller_pay_xingshendan(request):
    extdata = request.POST.get('extdata')
    if extdata == "115":
        paymoney = 10  # 10
    context = {
        "gameuser": request.POST.get('gameuser'),
        "paymoney": paymoney,
        "extdata": extdata,
    }
    return render(request, 'jump.html', context=context)


# 顶级技能自选包

def pay_jineng(request):
    context = {
        "title": "顶级技能自选包"
    }
    return render(request, 'pay_jineng.html', context=context)


def controller_pay_jineng(request):
    extdata = request.POST.get('extdata')
    if extdata == "116":
        paymoney = 20  # 20
    elif extdata == "117":
        paymoney = 50  # 50
    context = {
        "gameuser": request.POST.get('gameuser'),
        "paymoney": paymoney,
        "extdata": extdata,
    }
    return render(request, 'jump.html', context=context)


# 订单回执接口
def get_paidinfo(request):
    result = {
        'ordernumber': request.GET.get('ordernumber'),
        'userid': request.GET.get('userid'),
        'realmoney': request.GET.get('realmoney'),
        'gamecurrency': request.GET.get('gamecurrency'),
        'extdata': request.GET.get('extdata'),
        'sign': request.GET.get('sign')}
    print("验证秘钥")
    print(result)
    str_miyao = SECRET_KEYS + result.get('ordernumber')
    print(str_miyao)
    key1 = hashlib.md5(str_miyao.encode(encoding='utf-8')).hexdigest()
    print(key1)
    if result.get('sign') == key1:
        # 订单验证码对了就创建数据库信息，默认success是0，防止重复发放
        OrderList.objects.get_or_create(order_info=result)
        result_id = take_item.delay(result)
        print(result_id)
        return HttpResponse("ok")
    else:
        return HttpResponse("验证失败！")


def my_attribute(request):
    if request.method == 'GET':
        zhuan_list= [[1, 0], [2, 0], [3, 0], [4, 0], [5, 0],
                       [6, 0], [7, 0], [8, 0], [9, 0]]
        return render(request, 'My_attribute.html', context=locals())
    elif request.method == 'POST':
        print("这里是post了")
        print(request.POST)
        level = int(request.POST.get('level_now'))
        result = (level - 1) * 5
        zhuan_1 = int(request.POST.get('zhuan_1'))
        if zhuan_1:
            result += (zhuan_1 - 50) * 5 + 2000
        zhuan_2 = int(request.POST.get('zhuan_2'))
        if zhuan_2:
            result += (zhuan_2 - 50) * 5 + 2000
        zhuan_3 = int(request.POST.get('zhuan_3'))
        if zhuan_3:
            result += (zhuan_3 - 50) * 5 + 2000
        zhuan_4 = int(request.POST.get('zhuan_4'))
        if zhuan_4:
            result += (zhuan_4 - 50) * 5 + 2000
        zhuan_5 = int(request.POST.get('zhuan_5'))
        if zhuan_5:
            result += (zhuan_5 - 50) * 5 + 2000
        zhuan_6 = int(request.POST.get('zhuan_6'))
        if zhuan_6:
            result += (zhuan_6 - 50) * 5 + 2000
        zhuan_7 = int(request.POST.get('zhuan_7'))
        if zhuan_7:
            result += (zhuan_7 - 50) * 5 + 2000
        zhuan_8 = int(request.POST.get('zhuan_8'))
        if zhuan_8:
            result += (zhuan_8 - 50) * 5 + 2000
        zhuan_9 = int(request.POST.get('zhuan_9'))
        if zhuan_9:
            result += (zhuan_9 - 50) * 5 + 2000

        print(result)
        return render(request, 'My_attribute.html',
                      context={'result': result, 'zhuan_list': [[1,zhuan_1], [2,zhuan_2], [3,zhuan_3], [4,zhuan_4], [5,zhuan_5],
                                                                [6,zhuan_6], [7,zhuan_7], [8,zhuan_8], [9,zhuan_9]],
                               'level_now':level})

templates/My_attribute.html
{% extends 'mz.html' %}
{% block content %}
    <h4 style="color: #ff6600">您当前属性为:{{ result|default:'还未计算' }}</h4>
    <form class="form-horizontal" action="{% url 'pay:myattribute' %}" method="post">
        <div class="form-group">
            <label class="col-sm-2 control-label" >当前等级</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="level_now" placeholder="当前等级" value="{{ level_now }}">
            </div>
        </div>

        {% for zhuan in zhuan_list %}
            <div class="form-group">
                <label class="col-sm-2 control-label">{{ zhuan.0 }}转</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="zhuan_{{ zhuan.0 }}"
                            value="{{ zhuan.1 }}">
                </div>
            </div>
        {% endfor %}



        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">计 算</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/jump.html
<meta http-equiv="refresh" content="0;url=http://pay.6799wan.com/Payment/WapService/68f7c98632056cd786f6e367d6afb0d7?gameuser={{gameuser}}&paymoney={{paymoney}}&extdata={{extdata}}">
<h2>充值页面跳转中。。。</h2>

templates/mz.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" class="pixel-ratio-1 gr__mz_cgic_cn_com">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    {% load static %}
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
    <title>{{title}}</title>
    <meta name="generator" content="">
    <meta name="author" content="">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link href="{% static 'css/weui.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'css/jquery-weui.min.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'css/pay.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'css/nivoslider.css' %}" type="text/css" rel="stylesheet">
    {#    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->#}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

{#<!-- 可选的 Bootstrap 主题文件（一般不用引入） -->#}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

{#<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->#}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/top.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-weui.min.js' %}"></script>
    <style>
        .paymode {
            margin-bottom: 5px;
        }
    </style>
</head>
<body>
<div class="pay_index_chose_box">
    <div id="wrapper">
        <div class="bx-wrapper" style="max-width: 100%;">
            <div class="bx-viewport" style="width: 100%; overflow: hidden; position: relative; height: 252px;">
                <ul id="slider1"
                    style="width: 315%; position: relative; transition-duration: 0s; transform: translate3d(-720px, 0px, 0px);">
                    <li style="float: left; list-style: none; position: relative; width: 720px;" class="bx-clone"><a
                            href="javascript:;"><img src="{% static 'img/1572121512.jpg' %}" alt=""></a></li>
                    <li style="float: left; list-style: none; position: relative; width: 720px;"><a href="javascript:;"><img
                            src="{% static 'img/1572121512.jpg' %}" alt=""></a></li>

                    <li style="float: left; list-style: none; position: relative; width: 720px;" class="bx-clone"><a
                            href="javascript:;"><img src="{% static 'img/1572121512.jpg' %}" alt=""></a></li>
                </ul>
            </div>
            <div class="bx-controls bx-has-pager">
                <div class="bx-pager bx-default-pager">
                    <div class="bx-pager-item"><a href="{% url 'pay:index' %}" data-slide-index="0"
                                                  class="bx-pager-link active">1</a></div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'js/jquery.bxslider.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#slider1').bxSlider({
                auto: true,
                controls: false//隐藏左右按钮
            });
        });
    </script>

    <style>
        .weui-cells, .weui-cells::after, .weui-cells::before {
            border: none;
            margin-top: 0;
        }
    </style>

    <div class="weui-flex" style="padding-bottom:10px;">
        <div class="weui-flex__item">
            <a class="ta1" href="https://pan.baidu.com/s/1j98Bp4OeoJ-7usa0hJZUMA" target="_blank"><img class="img1"
                                                                                        src="{% static 'img/113.png' %}"></a>
            <p class="tc"><a class="ta2" href="https://pan.baidu.com/s/1j98Bp4OeoJ-7usa0hJZUMA" target="_blank">游戏下载 密码：2333</a></p>
        </div>
        <div class="weui-flex__item">
            <a class="ta1" href="http://pay.6799wan.com/Payment/WapService/8df7991802b1f5c8489aa89ef969c06c"
               target="_blank"><img class="img1" src="{% static 'img/111.png' %}"></a>
            <p class="tc"><a class="ta2"
                             href="http://pay.6799wan.com/Payment/WapService/8df7991802b1f5c8489aa89ef969c06c"
                             target="_blank">元宝赞助(暂未开通)</a></p>
        </div>
        <div class="weui-flex__item">
            <a class="ta1" href="{% url 'pay:index' %}" target="_blank"><img class="img1"
                                                                                             src="{% static 'img/112.png' %}"></a>
            <p class="tc"><a class="ta2" href="{% url 'pay:index' %}" >道具礼包</a></p>
        </div>
        <div class="weui-flex__item">
            <a class="ta1" href="http://111.229.222.18:66/" target="_blank"><img class="img1"
                                                                                  src="{% static 'img/114.png' %}"></a>
            <p class="tc"><a class="ta2" href="http://111.229.222.18:66/" target="_blank">游戏后台</a></p>
        </div>
    </div>





    <div class="paymode">
        <div class="head">
            <div class="weui-cells__title">赞助礼包（赞助金将用于升级服务器配置）</div>
        </div>
        {% block content %}
        <div class="body">
            <div class="weui-flex">
                <div class="weui-flex__item">
                    <div class="probox">
                        <a href="{% url 'pay:jin66' %}"> 金柳露礼包</a>
                        <b>软妹币20=2000</b>
                    </div>
                </div>
                <div class="weui-flex__item">
                    <div class="probox">
                        <a href="{% url 'pay:sancai' %}">三才勾玉礼包</a>
                        <b>软妹币58=999</b>
                    </div>
                </div>

                <div class="weui-flex__item">
                    <div class="probox">
                        <a href="{% url 'pay:renshenguo' %}">人参果礼包</a>
                        <b>软妹币10=388</b>
                    </div>
                </div>
            </div>
            <div class="weui-flex">
                <div class="weui-flex__item">
                    <div class="probox">
                        <a href="{% url 'pay:xingshendan' %}">醒神丹礼包</a>
                        <b>软妹币10=388</b>
                    </div>
                </div>
                <div class="weui-flex__item">
                    <div class="probox">
                        <a href="{% url 'pay:jineng' %}">顶级技能自选包</a>
                        <b>软妹币20=20</b>
                    </div>
                </div>
                                {% comment %}
                <div class="weui-flex__item">
                    <div class="probox">
                        <a href="http://mz.cgic.cn.com/gift_post.php?gameid=4&amp;infoid=56">金柳露包</a>
                        <b>赞助：¥10</b>
                    </div>
                </div>
            </div>
            <div class="weui-flex">
                <div class="weui-flex__item">
                    <div class="probox">
                        <a href="http://mz.cgic.cn.com/gift_post.php?gameid=4&amp;infoid=55">绑定元宝</a>
                        <b>赞助：¥100</b>
                    </div>
                </div>
                <div class="weui-flex__item">
                    <div class="probox">
                        <a href="http://mz.cgic.cn.com/gift_post.php?gameid=4&amp;infoid=54">绑定元宝</a>
                        <b>赞助：¥50</b>
                    </div>
                </div>
                <div class="weui-flex__item">
                    <div class="probox">
                        <a href="http://mz.cgic.cn.com/gift_post.php?gameid=4&amp;infoid=53">绑定元宝</a>
                        <b>赞助：¥10</b>
                    </div>
                </div>
                {% endcomment %}
            </div>
            <div class="weui-flex"></div>
        </div>
        {% endblock %}
    </div>

{% comment %}
    <div class="paymode">
        <div class="head">
            <div class="weui-cells__title">游戏攻略</div>
        </div>
        <div class="">
            <div class="weui-cells">
                <a class="weui-cell weui-cell_access" href="http://mz.cgic.cn.com/productshow.php?cid=23&amp;id=22">
                    <div class="weui-cell__bd">
                        <p>游戏攻略</p>
                    </div>
                    <div class="weui-cell__ft">
                    </div>
                </a>
                <a class="weui-cell weui-cell_access" href="http://mz.cgic.cn.com/productshow.php?cid=23&amp;id=21">
                    <div class="weui-cell__bd">
                        <p>门派特性</p>
                    </div>
                    <div class="weui-cell__ft">
                    </div>
                </a>
                <a class="weui-cell weui-cell_access" href="http://mz.cgic.cn.com/productshow.php?cid=23&amp;id=20">
                    <div class="weui-cell__bd">
                        <p>掉落详情</p>
                    </div>
                    <div class="weui-cell__ft">
                    </div>
                </a>
                <a class="weui-cell weui-cell_access" href="http://mz.cgic.cn.com/productshow.php?cid=23&amp;id=19">
                    <div class="weui-cell__bd">
                        <p>神器属性</p>
                    </div>
                    <div class="weui-cell__ft">
                    </div>
                </a>
            </div>
        </div>
    </div>
    {% endcomment %}
</div>
<div class="banquan">&nbsp;&nbsp;</div>
<!--<div class="pay_footer">
<p>Copyright © 2019</p>
</div>-->
<script type="text/javascript">

</script>
<div class="tbox" style="display: none;"><a href="javascript:void(0)" id="gotop"></a></div>
</body>
</html>

templates/pay_jin66.html
{% extends 'mz.html' %}
{% block content %}
    <form class="form-inline" action="{% url 'pay:cjin66' %}" method="post">
        <div class="form-group">
            <label for="exampleInputName2">角色名</label>
            <input type="text" class="form-control" name="gameuser" placeholder="角色名">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail2">购买数量</label>
            <select class="form-control" name="extdata">

                <option value="111">20软妹币2000个</option>
                <option value="112">50软妹币6000个</option>
            </select>

        </div>
        <button type="submit" class="btn btn-default">点击购买</button>
    </form>
    <h2 style="color: red">[金柳露礼包]
    </h2>
    <h3 style="color: red">
        比例： <u style="color: #49b7fe;" >
    20软妹币=2000个</u>
    <br>
        <u style="color: #49b7fe;" >
                50软妹币=6000个</u>
</h3>
{% endblock %}

templates/pay_jineng.html
{% extends 'mz.html' %}
{% block content %}
    <form class="form-inline" action="{% url 'pay:cjineng' %}" method="post">
        <div class="form-group">
            <label for="exampleInputName2">角色名</label>
            <input type="text" class="form-control" name="gameuser" placeholder="角色名">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail2">购买数量</label>
            <select class="form-control" name="extdata"value>
                <option value="116">20软妹币20个</option>
                <option value="117">50软妹币60个</option>
            </select>
            {#    <input type="text" class="form-control" name="n" placeholder="购买组数,1组=5个=1元">#}
        </div>
        <button type="submit" class="btn btn-default">点击充值</button>
    </form>
    <h2  style="color: red">[顶级技能自选礼包]</h2>
        <br>
    <h3 style="color: red">
        比例： <u style="color: #49b7fe;" >20软妹币=20个
    <br>
    50软妹币=60个</u>

</h3>
{% endblock %}

templates/pay_renshenguo.html
{% extends 'mz.html' %}
{% block content %}
    <form class="form-inline" action="{% url 'pay:crenshenguo' %}" method="post">
        <div class="form-group">
            <label for="exampleInputName2">角色名</label>
            <input type="text" class="form-control" name="gameuser" placeholder="角色名">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail2">购买数量</label>
            <select class="form-control" name="extdata">
                <option value="114">10软妹币388个</option>
            </select>
            {#    <input type="text" class="form-control" name="n" placeholder="购买组数,1组=5个=1元">#}
        </div>
        <button type="submit" class="btn btn-default">点击充值</button>
    </form>
    <h2 style="color: red">[人参果礼包]</h2>
        <br>
    <h3 style="color: red">
        比例： <u style="color: #49b7fe;" >10软妹币=388个</u>

</h3>
{% endblock %}

templates/pay_sancai.html
{% extends 'mz.html' %}
{% block content %}
    <form class="form-inline" action="{% url 'pay:csancai' %}" method="post">
        <div class="form-group">
            <label for="exampleInputName2">角色名</label>
            <input type="text" class="form-control" name="gameuser" placeholder="角色名">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail2">购买数量</label>
            <select class="form-control" name="extdata">
                <option value="113">58软妹币999个</option>
            </select>
            {#    <input type="text" class="form-control" name="n" placeholder="购买组数,1组=5个=1元">#}
        </div>
        <button type="submit" class="btn btn-default">点击充值</button>
    </form>
    <h2 style="color: red">[三才勾玉礼包]</h2>
        <br>
    <h3 style="color: red">
        比例： <u style="color: #49b7fe;" >58软妹币=999个</u>
        </h3>
    <hr>
    <h4>
<p style="color: #fe79de;">（如合成的宠物不需要，可以分解成333个三才勾玉！或者保留后续更新新神兽再使用！）</p>

</h4>
{% endblock %}

templates/pay_xingshendan.html
{% extends 'mz.html' %}
{% block content %}
    <form class="form-inline" action="{% url 'pay:cxingshendan' %}" method="post">
        <div class="form-group">
            <label for="exampleInputName2">角色名</label>
            <input type="text" class="form-control" name="gameuser" placeholder="角色名">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail2">购买数量</label>
            <select class="form-control" name="extdata">
                <option value="115">10软妹币388个</option>

            </select>
            {#    <input type="text" class="form-control" name="n" placeholder="购买组数,1组=5个=1元">#}
        </div>
        <button type="submit" class="btn btn-default">点击充值</button>
    </form>
    <h2 style="color: red">[醒神丹礼包]</h2>
        <br>
    <h3 style="color: red">
        比例： <u style="color: #49b7fe;" >10软妹币=388个</u>

</h3>
{% endblock %}

templates/waitting_pay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>等待支付</title>
</head>
<body>

</body>
</html>